# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'json_jmx.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 450)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setMaximumSize(QtCore.QSize(600, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 541, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(30, 20, 501, 81))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_json2jmx = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_json2jmx.setGeometry(QtCore.QRect(220, 90, 101, 21))
        self.pushButton_json2jmx.setObjectName("pushButton_json2jmx")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(72, 32, 421, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_file_path = QtWidgets.QLabel(self.layoutWidget1)
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout.addWidget(self.label_file_path)
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_file_path.setMinimumSize(QtCore.QSize(133, 20))
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.horizontalLayout.addWidget(self.lineEdit_file_path)
        self.pushButton_file_path = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_file_path.setObjectName("pushButton_file_path")
        self.horizontalLayout.addWidget(self.pushButton_file_path)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.textBrowser_logger = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_logger.setGeometry(QtCore.QRect(10, 20, 521, 91))
        self.textBrowser_logger.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.textBrowser_logger.setTabChangesFocus(False)
        self.textBrowser_logger.setUndoRedoEnabled(False)
        self.textBrowser_logger.setReadOnly(True)
        self.textBrowser_logger.setOverwriteMode(False)
        self.textBrowser_logger.setObjectName("textBrowser_logger")
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jmx自动生成工具"))
        self.groupBox_3.setTitle(_translate("MainWindow", "使用说明"))
        self.label.setText(_translate("MainWindow", "此程序可将.json格式接口文件转换成.jmx格式，方便接口自动化\n"
"1.Yapi上选择按【swaggerjson】导出方式导出，或在swagger平台选择【OpenAPI】导\n"
"出;\n"
"2.选择导出的.json所在目录;\n"
"3.生成jmx文件选择保存路径;"))
        self.groupBox_2.setTitle(_translate("MainWindow", "JSON_To_JMX"))
        self.pushButton_json2jmx.setText(_translate("MainWindow", "生成jmx文件"))
        self.label_file_path.setText(_translate("MainWindow", "JSON目录："))
        self.pushButton_file_path.setText(_translate("MainWindow", "浏览"))
        self.groupBox.setTitle(_translate("MainWindow", "日志"))
